apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: strace
spec:
  version: "v0.0.1"
  homepage: https://github.com/michaelwasher/kstrace
  shortDescription: "Captures strace logs from a running workload in the Kubernetes cluster"
  description: |
    kubectl-strace is a kubectl plugin that provides the ability to easily perform debugging of system-calls 
    for applications running in the cluster. kubectl-strace starts a priviledged Pod and attaches an strace instance
    to one or many running Pods, displaying or collecting the results for later review.
    Read more documentation see: https://github.com/michaelwasher/kstrace
  caveats: |
    This plugin requires the RBAC authority to start privileged Pods and create Namespaces
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/MichaelWasher/kstrace/releases/download/v0.0.1/kubectl-strace-darwin-amd64-v0.0.1.tar
    sha256: 6498f4ae3ebe61c39895b3e86687528edeaea07a8c14744ff9c15cd2b3b9ac2f
    files:
    - from: "kubectl-strace"
      to: "."
    - from: "LICENSE"
      to: "."
    bin: kubectl-strace
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/MichaelWasher/kstrace/releases/download/v0.0.1/kubectl-strace-linux-amd64-v0.0.1.tar
    sha256: dd23367832fc3be74aa631a1c9836c60db52b76e36fd7f740ecafce411dd1291
    files:
    - from: "kubectl-strace"
      to: "."
    - from: "LICENSE"
      to: "."
    bin: kubectl-strace
    