name: End to End Testing (k3d)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: AbsaOSS/k3d-action@v1.5.0
      name: "Create cluster"
      with:
        cluster-name: "test"
        args: --agents 1

    - name: "Perform e2e tests"
      run: |
        kubectl config use-context k3d-test
        kubectl cluster-info
        make test-e2e
