name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get Release Version
        id: source_tag
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build Release Artifacts
        run: |
          go version
          make VERSION=$VERSION release 
        env:
          VERSION: ${{ steps.source_tag.outputs.SOURCE_TAG }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kubectl-strace-*.tar
          body: |
            Kstrace Version ${{ steps.source_tag.outputs.SOURCE_TAG }}  Release.
            Release commit: ${{github.sha}}
          draft: false
          prerelease: false


      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.40

